### ISSUE TITLE
`cqcp_m5`: remove conversion of p_id or update documentation and `cqcp_check_input`

### ISSUE THREAD

**Issue by dafenner** [dafenner/CrowdQCplus#30]
Conversion
https://github.com/dafenner/CrowdQCplus/blob/4f95e7b2647e5a3bacf714ee70f2ac610ab6eab9/R/cqcp_filter.R#L379

leads to an error (no buddies) if p_id is not of type integer (thanks @falk-env for #29).

Either remove conversion, which could increase computation time, or update documentation and improve `cqcp_check_input`

**Comment by prayer007** [comment]
Had the same issue and now i use a workaround with an adapted function with assignInNamespace()

**Comment by dafenner** [comment]
Conversion removed, a new conversion introduced if `p_id` is of type integer:

https://github.com/dafenner/CrowdQCplus/blob/35959f90de3f959f29dfc799580523e2045cb1b7/R/cqcp_filter.R#LL373C1-L376C4.

[README updated](https://github.com/dafenner/CrowdQCplus/tree/master#data), `cqcp_check_input` now also included a check on data types.
