### ISSUE TITLE
Problem with uploading data table

### ISSUE THREAD

**Issue by reemeslam13** [dafenner/CrowdQCplus#32]
After going through the steps, when i run this code i get this problem 
# Load libraries
library(data.table)
library(CrowdQCplus)

# Data & input check
data <-fread("/Users/reemeslam/Downloads/Master Thesis /CrowdQCplus-master/Bamberg_March_Data.txt")
ok <- cqcp_check_input(data)

# Perform complete QC
if(ok) {
   data_qc <- cqcp_qcCWS(data) # QC   
   n_data_qc <- cqcp_output_statistics(data_qc) # output statistics
}

I get this error 
Error in r[i1] - r[-length(r):-(length(r) - lag + 1L)] : 
  non-numeric argument to binary operator
Can you please post more detailed example with data format to help me figure out the problem 

[Bamberg_March_Data.txt](https://github.com/dafenner/CrowdQCplus/files/11268136/Bamberg_March_Data.txt)
<img width="533" alt="Screenshot 2023-04-19 at 05 12 33" src="https://user-images.githubusercontent.com/16979703/232957404-4e0d5f29-f0a6-4c8e-a72e-d828c9f2ffaa.png">

**Comment by dafenner** [comment]
Thanks @reemeslam13 for posting this and providing example data.
I could reproduce your error and it is related to the data type of your `time` column, which needs to be POSIXct.
After fixing that, it should work fine:

![grafik](https://user-images.githubusercontent.com/71379384/232998312-494dc230-d0bc-4b38-b572-325d8fb9a766.png)

I will include a check for correct data type in the next release (#33).
