### ISSUE TITLE
NaN values 

### ISSUE THREAD

**Issue by reemeslam13** [dafenner/CrowdQCplus#34]
[Bamberg_Stations 01.04.2023to30.04.2023.txt](https://github.com/dafenner/CrowdQCplus/files/11678918/Bamberg_Stations.01.04.2023to30.04.2023.txt)
for None value at certain time data entry it is filled as NaN however on running data on crowdQC+ it gives me this error,
Error in eval(ei, envir) : 
  Not compatible with requested type: [type=character; target=double].

and when i fill it with 999 gives mes this error 
  [CrowdQC+] Dimensions are off, are you sure your data set contain an NaN value for each p_id at each missing time step?

So the NaN data how it should be filled ?

**Comment by dafenner** [comment]
New release just published and master branch up to date (https://github.com/dafenner/CrowdQCplus/releases/tag/v1.0.2).
Let me know if you have further questions.

**Comment by dafenner** [comment]
Closing the issue, let me know if something isn't working @reemeslam13
