### ISSUE TITLE
Station buddies and their mean in m5

### ISSUE THREAD

**Issue by reemeslam13** [dafenner/CrowdQCplus#41]
is there a function that i can use to know station buddies ? and their mean for m5 ?

**Comment by dafenner** [comment]
No, there is no function in CrowdQC+ that provides those information as output.
The calculations are done per time step, so it's a bit difficult so say what you mean by "their mean for m5". You mean per time step?
You could of course look into [the m5 function](https://github.com/dafenner/CrowdQCplus/blob/35959f90de3f959f29dfc799580523e2045cb1b7/R/cqcp_filter.R#L341) to see how the buddies are identified and how the statistics are calculated and then write a little function that outputs the desired information.
